package main

import (
	_ "github.com/mtps/protoc-gen-cryptids/crypt"
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + "_crypt.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-cryptids")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P("\"crypto\"")
	g.P(")")
	g.P()
	for _, message := range file.Messages {
		g.P("type ", message.GoIdent.GoName, " struct {")
		g.P("}")
		g.P()
		for _, field := range message.Fields {
			g.P("type ", field.GoIdent.GoName, " struct {")
			g.P("}")
			g.P()
		}
	}
	return g
}
