// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: crypt/crypt.proto

package cryptpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sensitive     bool                   `protobuf:"varint,1,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_crypt_crypt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_crypt_crypt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_crypt_crypt_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

var file_crypt_crypt_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         8675305,
		Name:          "crypt.opts",
		Tag:           "bytes,8675305,opt,name=opts",
		Filename:      "crypt/crypt.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional crypt.FieldOptions opts = 8675305;
	E_Opts = &file_crypt_crypt_proto_extTypes[0]
)

var File_crypt_crypt_proto protoreflect.FileDescriptor

var file_crypt_crypt_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x72, 0x79, 0x70, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x0c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x3a, 0x4b, 0x0a, 0x04, 0x6f, 0x70,
	0x74, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xe9, 0xbf, 0x91, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x42, 0x62, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x65,
	0x78, 0x74, 0x42, 0x0a, 0x43, 0x72, 0x79, 0x70, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x3b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x2f, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x3b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_crypt_crypt_proto_rawDescOnce sync.Once
	file_crypt_crypt_proto_rawDescData = file_crypt_crypt_proto_rawDesc
)

func file_crypt_crypt_proto_rawDescGZIP() []byte {
	file_crypt_crypt_proto_rawDescOnce.Do(func() {
		file_crypt_crypt_proto_rawDescData = protoimpl.X.CompressGZIP(file_crypt_crypt_proto_rawDescData)
	})
	return file_crypt_crypt_proto_rawDescData
}

var file_crypt_crypt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_crypt_crypt_proto_goTypes = []any{
	(*FieldOptions)(nil),                // 0: crypt.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_crypt_crypt_proto_depIdxs = []int32{
	1, // 0: crypt.opts:extendee -> google.protobuf.MessageOptions
	0, // 1: crypt.opts:type_name -> crypt.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crypt_crypt_proto_init() }
func file_crypt_crypt_proto_init() {
	if File_crypt_crypt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crypt_crypt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_crypt_crypt_proto_goTypes,
		DependencyIndexes: file_crypt_crypt_proto_depIdxs,
		MessageInfos:      file_crypt_crypt_proto_msgTypes,
		ExtensionInfos:    file_crypt_crypt_proto_extTypes,
	}.Build()
	File_crypt_crypt_proto = out.File
	file_crypt_crypt_proto_rawDesc = nil
	file_crypt_crypt_proto_goTypes = nil
	file_crypt_crypt_proto_depIdxs = nil
}
