// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: crypt/types.proto

package cryptpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EString is a wrapper for an encrypted string.
type EString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EString) Reset() {
	*x = EString{}
	mi := &file_crypt_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EString) ProtoMessage() {}

func (x *EString) ProtoReflect() protoreflect.Message {
	mi := &file_crypt_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EString.ProtoReflect.Descriptor instead.
func (*EString) Descriptor() ([]byte, []int) {
	return file_crypt_types_proto_rawDescGZIP(), []int{0}
}

func (x *EString) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_crypt_types_proto protoreflect.FileDescriptor

var file_crypt_types_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x72, 0x79, 0x70, 0x74, 0x22, 0x1f, 0x0a, 0x07, 0x45, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x5f, 0x0a, 0x1e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x74, 0x70, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x42, 0x0a, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x74, 0x70, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x64, 0x73, 0x2f, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x3b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_crypt_types_proto_rawDescOnce sync.Once
	file_crypt_types_proto_rawDescData = file_crypt_types_proto_rawDesc
)

func file_crypt_types_proto_rawDescGZIP() []byte {
	file_crypt_types_proto_rawDescOnce.Do(func() {
		file_crypt_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_crypt_types_proto_rawDescData)
	})
	return file_crypt_types_proto_rawDescData
}

var file_crypt_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_crypt_types_proto_goTypes = []any{
	(*EString)(nil), // 0: crypt.EString
}
var file_crypt_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crypt_types_proto_init() }
func file_crypt_types_proto_init() {
	if File_crypt_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crypt_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crypt_types_proto_goTypes,
		DependencyIndexes: file_crypt_types_proto_depIdxs,
		MessageInfos:      file_crypt_types_proto_msgTypes,
	}.Build()
	File_crypt_types_proto = out.File
	file_crypt_types_proto_rawDesc = nil
	file_crypt_types_proto_goTypes = nil
	file_crypt_types_proto_depIdxs = nil
}
